// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// autotunegg_bcd
List autotunegg_bcd(arma::mat xin, arma::vec yin, arma::uvec group, float alpha, bool standardize, bool standardize_response, bool intercept, bool active, float tau, bool trace_it, double sigma_tolerance, double beta_tolerance, short int sigma_iter_max, short int active_iter_max, short int beta_iter_max);
RcppExport SEXP _autotunegg_autotunegg_bcd(SEXP xinSEXP, SEXP yinSEXP, SEXP groupSEXP, SEXP alphaSEXP, SEXP standardizeSEXP, SEXP standardize_responseSEXP, SEXP interceptSEXP, SEXP activeSEXP, SEXP tauSEXP, SEXP trace_itSEXP, SEXP sigma_toleranceSEXP, SEXP beta_toleranceSEXP, SEXP sigma_iter_maxSEXP, SEXP active_iter_maxSEXP, SEXP beta_iter_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize_response(standardize_responseSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Rcpp::traits::input_parameter< float >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type trace_it(trace_itSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_tolerance(sigma_toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type beta_tolerance(beta_toleranceSEXP);
    Rcpp::traits::input_parameter< short int >::type sigma_iter_max(sigma_iter_maxSEXP);
    Rcpp::traits::input_parameter< short int >::type active_iter_max(active_iter_maxSEXP);
    Rcpp::traits::input_parameter< short int >::type beta_iter_max(beta_iter_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(autotunegg_bcd(xin, yin, group, alpha, standardize, standardize_response, intercept, active, tau, trace_it, sigma_tolerance, beta_tolerance, sigma_iter_max, active_iter_max, beta_iter_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_autotunegg_autotunegg_bcd", (DL_FUNC) &_autotunegg_autotunegg_bcd, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_autotunegg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
