# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autotunegg_bcd <- function(xin, yin, group, alpha = 0.01, standardize = TRUE, standardize_response = TRUE, intercept = TRUE, active = FALSE, tau = 0.5, trace_it = FALSE, sigma_tolerance = 1e-8, beta_tolerance = 1e-8, sigma_iter_max = 100L, active_iter_max = 100L, beta_iter_max = 100L) {
    .Call('_autotunegg_autotunegg_bcd', PACKAGE = 'autotunegg', xin, yin, group, alpha, standardize, standardize_response, intercept, active, tau, trace_it, sigma_tolerance, beta_tolerance, sigma_iter_max, active_iter_max, beta_iter_max)
}

